import { ReactNode } from "react";
import { GiCard10Clubs, GiCard2Clubs } from "react-icons/gi";
export const card: { [key: string]: ReactNode } = {
  "2C": <GiCard10Clubs />,
};
export const cardComponents = {
  "2C": <GiCard2Clubs />,
  "3C": <GiCard3Clubs />,
  "4C": <GiCard4Clubs />,
  "5C": <GiCard5Clubs />,
  "6C": <GiCard6Clubs />,
  "7C": <GiCard7Clubs />,
  "8C": <GiCard8Clubs />,
  "9C": <GiCard9Clubs />,
  "10C": <GiCard10Clubs />,
  JC: <GiCardJClubs />,
  QC: <GiCardQClubs />,
  KC: <GiCardKClubs />,
  AC: <GiCardAClubs />,
  "2D": <GiCard2Diamonds />,
  "3D": <GiCard3Diamonds />,
  "4D": <GiCard4Diamonds />,
  "5D": <GiCard5Diamonds />,
  "6D": <GiCard6Diamonds />,
  "7D": <GiCard7Diamonds />,
  "8D": <GiCard8Diamonds />,
  "9D": <GiCard9Diamonds />,
  "10D": <GiCard10Diamonds />,
  JD: <GiCardJDiamonds />,
  QD: <GiCardQDiamonds />,
  KD: <GiCardKDiamonds />,
  AD: <GiCardADiamonds />,
  "2H": <GiCard2Hearts />,
  "3H": <GiCard3Hearts />,
  "4H": <GiCard4Hearts />,
  "5H": <GiCard5Hearts />,
  "6H": <GiCard6Hearts />,
  "7H": <GiCard7Hearts />,
  "8H": <GiCard8Hearts />,
  "9H": <GiCard9Hearts />,
  "10H": <GiCard10Hearts />,
  JH: <GiCardJHearts />,
  QH: <GiCardQHearts />,
  KH: <GiCardKHearts />,
  AH: <GiCardAHearts />,
  "2S": <GiCard2Spades />,
  "3S": <GiCard3Spades />,
  "4S": <GiCard4Spades />,
  "5S": <GiCard5Spades />,
  "6S": <GiCard6Spades />,
  "7S": <GiCard7Spades />,
  "8S": <GiCard8Spades />,
  "9S": <GiCard9Spades />,
  "10S": <GiCard10Spades />,
  JS: <GiCardJSpades />,
  QS: <GiCardQSpades />,
  KS: <GiCardKSpades />,
  AS: <GiCardASpades />,
};
